{% set name = "aeolus" %}
{% set version = "0.4.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/exoclim/aeolus/archive/{{ version }}.tar.gz
  sha256: 988e567608944e28425e5daa9b9fe5605552a54d336f059c7b74e52f2491c061

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - setuptools
    - pip
  run:
    - python >=3.7
    - cached-property
    - cartopy
    - cf-units
    - f90nml
    - iris >=3.0
    - latlon23
    - matplotlib-base
    - numpy
    - python-stratify

test:
  imports:
    - aeolus
    - aeolus.calc
    - aeolus.const
    - aeolus.coord
    - aeolus.model
    - aeolus.plot
    - aeolus.subset

about:
  home: https://github.com/exoclim/aeolus
  license: LGPL-3.0-only
  license_family: LGPL
  license_file: LICENSE
  summary: Python library for object-oriented analysis of atmospheric model output.
  description: |
    aeolus is a pure-Python library for object-oriented analysis for atmospheric model output built on top of the scitools iris package <https://github.com/SciTools/iris>. It also includes small extensions to interoperate with MetPy and PyVista.
  dev_url: https://github.com/exoclim/aeolus
  doc_url: https://exoclim.github.io/aeolus

extra:
  recipe-maintainers:
    - dennissergeev
