{% set name = "aeolus" %}
{% set version = "0.4.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/exoclim/aeolus/archive/{{ version }}.tar.gz
  sha256: 10dbe1ab01db22d1bbd193dd3326c5b269273330f89d40bee3b8205faebb2080

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - setuptools
    - pip
  run:
    - python >=3.7
    - cartopy
    - f90nml
    - iris >=2.4
    - latlon23
    - python-stratify

test:
  imports:
    - aeolus
    - aeolus.calc
    - aeolus.const
    - aeolus.model
    - aeolus.plot

about:
  home: https://github.com/exoclim/aeolus
  license: LGPL-3.0-only
  license_family: LGPL
  license_file: LICENSE
  summary: Python library for object-oriented analysis of atmospheric model output.
  description: |
    aeolus is a pure-Python library for object-oriented analysis for atmospheric model output built on top of the scitools iris package <https://github.com/SciTools/iris>. It also includes small extensions to interoperate with MetPy and PyVista.
  dev_url: https://github.com/exoclim/aeolus
  doc_url: https://exoclim.github.io/aeolus

extra:
  recipe-maintainers:
    - dennissergeev
