{% set name = "aeolus" %}
{% set version = "0.4.18" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/exoclim/aeolus/archive/{{ version }}.tar.gz
  sha256: 5ade6a686813cb1bf7a0534879979fa560a62937169c06be0d7340db6075a58a

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - setuptools
    - pip
  run:
    - scitools-iris >=3.4
    - python >=3.7
    - cached-property >=1.5.1
    - cartopy
    - cf-units
    - f90nml
    - iris >=3.0
    - latlon23 >=1.0.7
    - matplotlib-base >=3.6
    - numpy >=1.17.0
    - python-stratify

test:
  imports:
    - aeolus
    - aeolus.calc
    - aeolus.const
    - aeolus.coord
    - aeolus.model
    - aeolus.plot
    - aeolus.subset

about:
  home: https://github.com/exoclim/aeolus
  license: LGPL-3.0-only
  license_family: LGPL
  license_file: LICENSE
  summary: Python library for object-oriented analysis of atmospheric model output.
  description: |
    aeolus is a pure-Python library for object-oriented analysis for atmospheric model output built on top of the scitools iris package <https://github.com/SciTools/iris>. It also includes small extensions to interoperate with MetPy and PyVista.
  dev_url: https://github.com/exoclim/aeolus
  doc_url: https://exoclim.github.io/aeolus

extra:
  recipe-maintainers:
    - dennissergeev
